react.js
Adjusted this rule: 
- to give it a more html like behavior
=> feat(react): adjusted react/jsx-curly-brace-presence

react.js
_Note: only warn for better migration_
=> feat(react): turned react/jsx-filename-extension to warn

base.js
- turned off import/no-commonjs
- turned off import/unambiguous
=> feat(base): added proper webpack.config.js support

package.json
BREAKING CHANGE: renamed package
closes #16
=> refactor!: renamed package to @typedigital/eslint-config

base.js
=> feat: add ESlint 6.7.0 rules

base.js
add semicolons and other semicolon related rules
This PR closes #13
=> feat: add semi with warn

react.js
BREAKING CHANGE: this could break CI pipelines.
closes #30
=> refactor(react)!: consistent multiline in react

base.js
=> fix: no-extra-parens clashes with arrow-parens

base.js
- turned multiline-ternary off
closes #37
=> fix: weird ternary by turning rule off

base.js, package-lock.json, package.json, react-native.js, react.js
adjusted some rules and closes #26
=> feat: added eslint-node-plugin

base.js
=> fix: maximum statements per line should accept two statements

package-lock.json, package.json
These are only dependency updates.
=> chore: dependency update October 2020

base.js
it caused multiple errors in most projects
=> fix: removed node/recommended

base.js
Added a rule to fix the issue.
closes #36.
=> fix: bad code layouting by function parentheses

.gitignore, base.js, package-lock.json, package.json, tests/base/spacing.js
- removed some outdated rules
- added new babel plugin and parser
- added tests and removed `tests/**` from `.gitignore` 
closes #35
=> fix: unconsistent bracket spacing

base.js, package-lock.json, package.json, typescript.js
- updated dependencies
- added helpers for eslint rules and testing
- fixed lint errors
=> chore: updated dependencies

package-lock.json, package.json, styled-components.js, tests/styled-components/.eslintrc, tests/styled-components/components.ts, tests/styled-components/tsconfig.json
=> feat: add styled-components config

package-lock.json, package.json
- removed the `eslint-plugin-unicorn` as devDependency
- added it to the dependencies
- tested everything
=> fix: add missing unicorn plugin to dependencies

react.js, tests/react/test-component.jsx
- turned rule `react/no-multi-comp` off
- tested the behavior in the test for the react config
=> feat: turn off no-multi-comp to support colocation

base.js, package-lock.json, package.json, typescript.js
- Added new plugin
- Used rule from plugin and disabled valid-jsdoc for ts files
- Tested manually
=> feat: add tsdoc validation for ts files

.gitignore, .vscode/settings.json, package-lock.json, package.json, tests/typescript/helper.ts, tests/typescript/non-null-assertion.ts, tests/typescript/typescript.test.ts, typescript.js
- enabled warning for `no-non-null-assertion`
- added tests for
=> feat: enable warnings for non null assertion and add test framework

.github/workflows/tests.yml
- add you workflow file
- run tests
=> ci: add test workflow

README.md, styled-components.js
Added a Documentation for styled-components rules
=> feat: added documentation to styled components rules
